"""Add all base models

Revision ID: 1eb77480d509
Revises: 051bb67aae5b
Create Date: 2024-11-14 23:36:12.016873

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1eb77480d509"
down_revision: Union[str, None] = "051bb67aae5b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingredients",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipes_ingredients",
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("ingredient_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingredient_id"],
            ["ingredients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("recipe_id", "ingredient_id"),
    )
    op.create_table(
        "recipes_steps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("image_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["recipe_id"],
            ["recipes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("recipes", sa.Column("title", sa.String(), nullable=False))
    op.add_column(
        "recipes", sa.Column("created_at", sa.DateTime(), nullable=False)
    )
    op.add_column(
        "recipes", sa.Column("author_id", sa.Integer(), nullable=False)
    )
    op.alter_column(
        "recipes", "image_id", existing_type=sa.INTEGER(), nullable=False
    )
    op.create_foreign_key(None, "recipes", "users", ["author_id"], ["id"])
    op.drop_column("recipes", "stars")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipes",
        sa.Column("stars", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "recipes", type_="foreignkey")
    op.alter_column(
        "recipes", "image_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_column("recipes", "author_id")
    op.drop_column("recipes", "created_at")
    op.drop_column("recipes", "title")
    op.drop_table("recipes_steps")
    op.drop_table("recipes_ingredients")
    op.drop_table("users")
    op.drop_table("ingredients")
    # ### end Alembic commands ###
